/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 50
#define LARGE_STATE_COUNT 16
#define SYMBOL_COUNT 24
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 10
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_BSLASH = 1,
  anon_sym_COMMA = 2,
  anon_sym_DOT = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_LBRACK = 6,
  anon_sym_RBRACK = 7,
  anon_sym_PERCENT = 8,
  aux_sym_comment_token1 = 9,
  sym_variable = 10,
  sym_macro = 11,
  sym_string = 12,
  sym_directive = 13,
  sym_source_file = 14,
  sym__expression = 15,
  sym_function = 16,
  sym_application = 17,
  sym_dire_loop = 18,
  sym_comment = 19,
  aux_sym_source_file_repeat1 = 20,
  aux_sym_function_repeat1 = 21,
  aux_sym_application_repeat1 = 22,
  aux_sym_comment_repeat1 = 23,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_COMMA] = ",",
  [anon_sym_DOT] = ".",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_PERCENT] = "%",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_variable] = "variable",
  [sym_macro] = "macro",
  [sym_string] = "string",
  [sym_directive] = "directive",
  [sym_source_file] = "source_file",
  [sym__expression] = "_expression",
  [sym_function] = "function",
  [sym_application] = "application",
  [sym_dire_loop] = "dire_loop",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_function_repeat1] = "function_repeat1",
  [aux_sym_application_repeat1] = "application_repeat1",
  [aux_sym_comment_repeat1] = "comment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_variable] = sym_variable,
  [sym_macro] = sym_macro,
  [sym_string] = sym_string,
  [sym_directive] = sym_directive,
  [sym_source_file] = sym_source_file,
  [sym__expression] = sym__expression,
  [sym_function] = sym_function,
  [sym_application] = sym_application,
  [sym_dire_loop] = sym_dire_loop,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_function_repeat1] = aux_sym_function_repeat1,
  [aux_sym_application_repeat1] = aux_sym_application_repeat1,
  [aux_sym_comment_repeat1] = aux_sym_comment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_macro] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_application] = {
    .visible = true,
    .named = true,
  },
  [sym_dire_loop] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_application_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_arg = 1,
  field_body = 2,
  field_function = 3,
  field_variable = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arg] = "arg",
  [field_body] = "body",
  [field_function] = "function",
  [field_variable] = "variable",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 1},
  [7] = {.index = 8, .length = 2},
  [8] = {.index = 10, .length = 2},
  [9] = {.index = 12, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_variable, 0},
  [1] =
    {field_variable, 0, .inherited = true},
    {field_variable, 1, .inherited = true},
  [3] =
    {field_arg, 0},
  [4] =
    {field_body, 1},
  [5] =
    {field_body, 3},
    {field_variable, 1},
  [7] =
    {field_arg, 1},
  [8] =
    {field_arg, 2, .inherited = true},
    {field_function, 1},
  [10] =
    {field_arg, 0, .inherited = true},
    {field_arg, 1, .inherited = true},
  [12] =
    {field_body, 4},
    {field_variable, 1, .inherited = true},
    {field_variable, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 7,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 9,
  [14] = 11,
  [15] = 12,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 20,
  [25] = 19,
  [26] = 21,
  [27] = 22,
  [28] = 17,
  [29] = 29,
  [30] = 30,
  [31] = 29,
  [32] = 30,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 33,
  [40] = 40,
  [41] = 38,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 43,
  [47] = 45,
  [48] = 48,
  [49] = 49,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '%') ADVANCE(17);
      if (lookahead == '(') ADVANCE(13);
      if (lookahead == ')') ADVANCE(14);
      if (lookahead == ',') ADVANCE(11);
      if (lookahead == '.') ADVANCE(12);
      if (lookahead == '[') ADVANCE(15);
      if (lookahead == '\\') SKIP(7);
      if (lookahead == ']') ADVANCE(16);
      if (lookahead == '_') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('!' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          lookahead == '?' ||
          lookahead == '@') ADVANCE(24);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(22);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(4);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(4);
      if (lookahead == '\r') SKIP(1);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(23);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '%') ADVANCE(17);
      if (lookahead == ',') ADVANCE(11);
      if (lookahead == '.') ADVANCE(12);
      if (lookahead == '\\') SKIP(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 5:
      if (lookahead == '%') ADVANCE(17);
      if (lookahead == '\\') ADVANCE(18);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 6:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') SKIP(0);
      END_STATE();
    case 7:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '\r') SKIP(6);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '"', 3,
        '%', 17,
        '(', 13,
        ')', 14,
        ',', 11,
        '[', 15,
        '\\', 10,
        '_', 20,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('!' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          lookahead == '?' ||
          lookahead == '@') ADVANCE(24);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(22);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\\') ADVANCE(18);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '%') ADVANCE(18);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '_') ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(22);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_macro);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_directive);
      if (lookahead == '!' ||
          lookahead == '#' ||
          lookahead == '$' ||
          lookahead == '&' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '?' ||
          lookahead == '@') ADVANCE(24);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 8},
  [2] = {.lex_state = 8},
  [3] = {.lex_state = 8},
  [4] = {.lex_state = 8},
  [5] = {.lex_state = 8},
  [6] = {.lex_state = 8},
  [7] = {.lex_state = 8},
  [8] = {.lex_state = 8},
  [9] = {.lex_state = 8},
  [10] = {.lex_state = 8},
  [11] = {.lex_state = 8},
  [12] = {.lex_state = 8},
  [13] = {.lex_state = 8},
  [14] = {.lex_state = 8},
  [15] = {.lex_state = 8},
  [16] = {.lex_state = 8},
  [17] = {.lex_state = 8},
  [18] = {.lex_state = 8},
  [19] = {.lex_state = 8},
  [20] = {.lex_state = 8},
  [21] = {.lex_state = 8},
  [22] = {.lex_state = 8},
  [23] = {.lex_state = 8},
  [24] = {.lex_state = 8},
  [25] = {.lex_state = 8},
  [26] = {.lex_state = 8},
  [27] = {.lex_state = 8},
  [28] = {.lex_state = 8},
  [29] = {.lex_state = 4},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 4},
  [34] = {.lex_state = 5},
  [35] = {.lex_state = 5},
  [36] = {.lex_state = 4},
  [37] = {.lex_state = 4},
  [38] = {.lex_state = 4},
  [39] = {.lex_state = 4},
  [40] = {.lex_state = 5},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 4},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {(TSStateId)(-1),},
  [49] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(3),
    [sym_variable] = ACTIONS(1),
    [sym_macro] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_directive] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(44),
    [sym__expression] = STATE(23),
    [sym_function] = STATE(25),
    [sym_application] = STATE(25),
    [sym_dire_loop] = STATE(25),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_BSLASH] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(13),
    [sym_variable] = ACTIONS(15),
    [sym_macro] = ACTIONS(15),
    [sym_string] = ACTIONS(15),
    [sym_directive] = ACTIONS(15),
  },
  [STATE(2)] = {
    [sym__expression] = STATE(16),
    [sym_function] = STATE(19),
    [sym_application] = STATE(19),
    [sym_dire_loop] = STATE(19),
    [sym_comment] = STATE(2),
    [aux_sym_application_repeat1] = STATE(2),
    [anon_sym_BSLASH] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(20),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(26),
    [anon_sym_LBRACK] = ACTIONS(28),
    [anon_sym_PERCENT] = ACTIONS(13),
    [sym_variable] = ACTIONS(31),
    [sym_macro] = ACTIONS(31),
    [sym_string] = ACTIONS(31),
    [sym_directive] = ACTIONS(31),
  },
  [STATE(3)] = {
    [sym__expression] = STATE(16),
    [sym_function] = STATE(19),
    [sym_application] = STATE(19),
    [sym_dire_loop] = STATE(19),
    [sym_comment] = STATE(3),
    [aux_sym_application_repeat1] = STATE(2),
    [anon_sym_BSLASH] = ACTIONS(34),
    [anon_sym_COMMA] = ACTIONS(36),
    [anon_sym_LPAREN] = ACTIONS(38),
    [anon_sym_RPAREN] = ACTIONS(40),
    [anon_sym_LBRACK] = ACTIONS(42),
    [anon_sym_PERCENT] = ACTIONS(13),
    [sym_variable] = ACTIONS(44),
    [sym_macro] = ACTIONS(44),
    [sym_string] = ACTIONS(44),
    [sym_directive] = ACTIONS(44),
  },
  [STATE(4)] = {
    [sym__expression] = STATE(16),
    [sym_function] = STATE(19),
    [sym_application] = STATE(19),
    [sym_dire_loop] = STATE(19),
    [sym_comment] = STATE(4),
    [aux_sym_application_repeat1] = STATE(2),
    [anon_sym_BSLASH] = ACTIONS(34),
    [anon_sym_COMMA] = ACTIONS(36),
    [anon_sym_LPAREN] = ACTIONS(38),
    [anon_sym_RPAREN] = ACTIONS(46),
    [anon_sym_LBRACK] = ACTIONS(42),
    [anon_sym_PERCENT] = ACTIONS(13),
    [sym_variable] = ACTIONS(44),
    [sym_macro] = ACTIONS(44),
    [sym_string] = ACTIONS(44),
    [sym_directive] = ACTIONS(44),
  },
  [STATE(5)] = {
    [sym__expression] = STATE(23),
    [sym_function] = STATE(25),
    [sym_application] = STATE(25),
    [sym_dire_loop] = STATE(25),
    [sym_comment] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(48),
    [anon_sym_BSLASH] = ACTIONS(50),
    [anon_sym_LPAREN] = ACTIONS(53),
    [anon_sym_LBRACK] = ACTIONS(56),
    [anon_sym_PERCENT] = ACTIONS(13),
    [sym_variable] = ACTIONS(59),
    [sym_macro] = ACTIONS(59),
    [sym_string] = ACTIONS(59),
    [sym_directive] = ACTIONS(59),
  },
  [STATE(6)] = {
    [sym__expression] = STATE(23),
    [sym_function] = STATE(25),
    [sym_application] = STATE(25),
    [sym_dire_loop] = STATE(25),
    [sym_comment] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(62),
    [anon_sym_BSLASH] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(13),
    [sym_variable] = ACTIONS(15),
    [sym_macro] = ACTIONS(15),
    [sym_string] = ACTIONS(15),
    [sym_directive] = ACTIONS(15),
  },
  [STATE(7)] = {
    [sym__expression] = STATE(16),
    [sym_function] = STATE(19),
    [sym_application] = STATE(19),
    [sym_dire_loop] = STATE(19),
    [sym_comment] = STATE(7),
    [aux_sym_application_repeat1] = STATE(3),
    [anon_sym_BSLASH] = ACTIONS(34),
    [anon_sym_COMMA] = ACTIONS(36),
    [anon_sym_LPAREN] = ACTIONS(38),
    [anon_sym_LBRACK] = ACTIONS(42),
    [anon_sym_PERCENT] = ACTIONS(13),
    [sym_variable] = ACTIONS(44),
    [sym_macro] = ACTIONS(44),
    [sym_string] = ACTIONS(44),
    [sym_directive] = ACTIONS(44),
  },
  [STATE(8)] = {
    [sym__expression] = STATE(16),
    [sym_function] = STATE(19),
    [sym_application] = STATE(19),
    [sym_dire_loop] = STATE(19),
    [sym_comment] = STATE(8),
    [aux_sym_application_repeat1] = STATE(4),
    [anon_sym_BSLASH] = ACTIONS(34),
    [anon_sym_COMMA] = ACTIONS(36),
    [anon_sym_LPAREN] = ACTIONS(38),
    [anon_sym_LBRACK] = ACTIONS(42),
    [anon_sym_PERCENT] = ACTIONS(13),
    [sym_variable] = ACTIONS(44),
    [sym_macro] = ACTIONS(44),
    [sym_string] = ACTIONS(44),
    [sym_directive] = ACTIONS(44),
  },
  [STATE(9)] = {
    [sym__expression] = STATE(28),
    [sym_function] = STATE(25),
    [sym_application] = STATE(25),
    [sym_dire_loop] = STATE(25),
    [sym_comment] = STATE(9),
    [anon_sym_BSLASH] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(13),
    [sym_variable] = ACTIONS(15),
    [sym_macro] = ACTIONS(15),
    [sym_string] = ACTIONS(15),
    [sym_directive] = ACTIONS(15),
  },
  [STATE(10)] = {
    [sym__expression] = STATE(18),
    [sym_function] = STATE(19),
    [sym_application] = STATE(19),
    [sym_dire_loop] = STATE(19),
    [sym_comment] = STATE(10),
    [anon_sym_BSLASH] = ACTIONS(34),
    [anon_sym_LPAREN] = ACTIONS(38),
    [anon_sym_LBRACK] = ACTIONS(42),
    [anon_sym_PERCENT] = ACTIONS(13),
    [sym_variable] = ACTIONS(44),
    [sym_macro] = ACTIONS(44),
    [sym_string] = ACTIONS(44),
    [sym_directive] = ACTIONS(44),
  },
  [STATE(11)] = {
    [sym__expression] = STATE(27),
    [sym_function] = STATE(25),
    [sym_application] = STATE(25),
    [sym_dire_loop] = STATE(25),
    [sym_comment] = STATE(11),
    [anon_sym_BSLASH] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(13),
    [sym_variable] = ACTIONS(15),
    [sym_macro] = ACTIONS(15),
    [sym_string] = ACTIONS(15),
    [sym_directive] = ACTIONS(15),
  },
  [STATE(12)] = {
    [sym__expression] = STATE(7),
    [sym_function] = STATE(19),
    [sym_application] = STATE(19),
    [sym_dire_loop] = STATE(19),
    [sym_comment] = STATE(12),
    [anon_sym_BSLASH] = ACTIONS(34),
    [anon_sym_LPAREN] = ACTIONS(38),
    [anon_sym_LBRACK] = ACTIONS(42),
    [anon_sym_PERCENT] = ACTIONS(13),
    [sym_variable] = ACTIONS(44),
    [sym_macro] = ACTIONS(44),
    [sym_string] = ACTIONS(44),
    [sym_directive] = ACTIONS(44),
  },
  [STATE(13)] = {
    [sym__expression] = STATE(17),
    [sym_function] = STATE(19),
    [sym_application] = STATE(19),
    [sym_dire_loop] = STATE(19),
    [sym_comment] = STATE(13),
    [anon_sym_BSLASH] = ACTIONS(34),
    [anon_sym_LPAREN] = ACTIONS(38),
    [anon_sym_LBRACK] = ACTIONS(42),
    [anon_sym_PERCENT] = ACTIONS(13),
    [sym_variable] = ACTIONS(44),
    [sym_macro] = ACTIONS(44),
    [sym_string] = ACTIONS(44),
    [sym_directive] = ACTIONS(44),
  },
  [STATE(14)] = {
    [sym__expression] = STATE(22),
    [sym_function] = STATE(19),
    [sym_application] = STATE(19),
    [sym_dire_loop] = STATE(19),
    [sym_comment] = STATE(14),
    [anon_sym_BSLASH] = ACTIONS(34),
    [anon_sym_LPAREN] = ACTIONS(38),
    [anon_sym_LBRACK] = ACTIONS(42),
    [anon_sym_PERCENT] = ACTIONS(13),
    [sym_variable] = ACTIONS(44),
    [sym_macro] = ACTIONS(44),
    [sym_string] = ACTIONS(44),
    [sym_directive] = ACTIONS(44),
  },
  [STATE(15)] = {
    [sym__expression] = STATE(8),
    [sym_function] = STATE(19),
    [sym_application] = STATE(19),
    [sym_dire_loop] = STATE(19),
    [sym_comment] = STATE(15),
    [anon_sym_BSLASH] = ACTIONS(34),
    [anon_sym_LPAREN] = ACTIONS(38),
    [anon_sym_LBRACK] = ACTIONS(42),
    [anon_sym_PERCENT] = ACTIONS(13),
    [sym_variable] = ACTIONS(44),
    [sym_macro] = ACTIONS(44),
    [sym_string] = ACTIONS(44),
    [sym_directive] = ACTIONS(44),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(13), 1,
      anon_sym_PERCENT,
    ACTIONS(64), 1,
      anon_sym_BSLASH,
    STATE(16), 1,
      sym_comment,
    ACTIONS(66), 8,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      sym_variable,
      sym_macro,
      sym_string,
      sym_directive,
  [20] = 4,
    ACTIONS(13), 1,
      anon_sym_PERCENT,
    ACTIONS(68), 1,
      anon_sym_BSLASH,
    STATE(17), 1,
      sym_comment,
    ACTIONS(70), 8,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      sym_variable,
      sym_macro,
      sym_string,
      sym_directive,
  [40] = 4,
    ACTIONS(13), 1,
      anon_sym_PERCENT,
    ACTIONS(72), 1,
      anon_sym_BSLASH,
    STATE(18), 1,
      sym_comment,
    ACTIONS(74), 8,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      sym_variable,
      sym_macro,
      sym_string,
      sym_directive,
  [60] = 4,
    ACTIONS(13), 1,
      anon_sym_PERCENT,
    ACTIONS(76), 1,
      anon_sym_BSLASH,
    STATE(19), 1,
      sym_comment,
    ACTIONS(78), 8,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      sym_variable,
      sym_macro,
      sym_string,
      sym_directive,
  [80] = 4,
    ACTIONS(13), 1,
      anon_sym_PERCENT,
    ACTIONS(80), 1,
      anon_sym_BSLASH,
    STATE(20), 1,
      sym_comment,
    ACTIONS(82), 8,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      sym_variable,
      sym_macro,
      sym_string,
      sym_directive,
  [100] = 4,
    ACTIONS(13), 1,
      anon_sym_PERCENT,
    ACTIONS(84), 1,
      anon_sym_BSLASH,
    STATE(21), 1,
      sym_comment,
    ACTIONS(86), 8,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      sym_variable,
      sym_macro,
      sym_string,
      sym_directive,
  [120] = 4,
    ACTIONS(13), 1,
      anon_sym_PERCENT,
    ACTIONS(88), 1,
      anon_sym_BSLASH,
    STATE(22), 1,
      sym_comment,
    ACTIONS(90), 8,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      sym_variable,
      sym_macro,
      sym_string,
      sym_directive,
  [140] = 4,
    ACTIONS(13), 1,
      anon_sym_PERCENT,
    STATE(23), 1,
      sym_comment,
    ACTIONS(92), 2,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
    ACTIONS(94), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_variable,
      sym_macro,
      sym_string,
      sym_directive,
  [159] = 4,
    ACTIONS(13), 1,
      anon_sym_PERCENT,
    STATE(24), 1,
      sym_comment,
    ACTIONS(80), 2,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
    ACTIONS(82), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_variable,
      sym_macro,
      sym_string,
      sym_directive,
  [178] = 4,
    ACTIONS(13), 1,
      anon_sym_PERCENT,
    STATE(25), 1,
      sym_comment,
    ACTIONS(76), 2,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
    ACTIONS(78), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_variable,
      sym_macro,
      sym_string,
      sym_directive,
  [197] = 4,
    ACTIONS(13), 1,
      anon_sym_PERCENT,
    STATE(26), 1,
      sym_comment,
    ACTIONS(84), 2,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
    ACTIONS(86), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_variable,
      sym_macro,
      sym_string,
      sym_directive,
  [216] = 4,
    ACTIONS(13), 1,
      anon_sym_PERCENT,
    STATE(27), 1,
      sym_comment,
    ACTIONS(88), 2,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
    ACTIONS(90), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_variable,
      sym_macro,
      sym_string,
      sym_directive,
  [235] = 4,
    ACTIONS(13), 1,
      anon_sym_PERCENT,
    STATE(28), 1,
      sym_comment,
    ACTIONS(68), 2,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
    ACTIONS(70), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_variable,
      sym_macro,
      sym_string,
      sym_directive,
  [254] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(96), 1,
      anon_sym_COMMA,
    ACTIONS(98), 1,
      anon_sym_DOT,
    ACTIONS(100), 1,
      sym_variable,
    STATE(29), 1,
      sym_comment,
  [270] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(96), 1,
      anon_sym_COMMA,
    ACTIONS(100), 1,
      sym_variable,
    ACTIONS(102), 1,
      anon_sym_DOT,
    STATE(30), 1,
      sym_comment,
  [286] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(96), 1,
      anon_sym_COMMA,
    ACTIONS(100), 1,
      sym_variable,
    ACTIONS(104), 1,
      anon_sym_DOT,
    STATE(31), 1,
      sym_comment,
  [302] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(96), 1,
      anon_sym_COMMA,
    ACTIONS(100), 1,
      sym_variable,
    ACTIONS(106), 1,
      anon_sym_DOT,
    STATE(32), 1,
      sym_comment,
  [318] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(108), 1,
      sym_variable,
    STATE(33), 1,
      sym_comment,
    STATE(41), 1,
      aux_sym_function_repeat1,
  [331] = 3,
    ACTIONS(110), 1,
      anon_sym_PERCENT,
    ACTIONS(112), 1,
      aux_sym_comment_token1,
    STATE(34), 2,
      sym_comment,
      aux_sym_comment_repeat1,
  [342] = 4,
    ACTIONS(115), 1,
      anon_sym_PERCENT,
    ACTIONS(117), 1,
      aux_sym_comment_token1,
    STATE(35), 1,
      sym_comment,
    STATE(40), 1,
      aux_sym_comment_repeat1,
  [355] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(96), 1,
      anon_sym_COMMA,
    ACTIONS(100), 1,
      sym_variable,
    STATE(36), 1,
      sym_comment,
  [368] = 3,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(119), 1,
      sym_variable,
    STATE(37), 2,
      sym_comment,
      aux_sym_function_repeat1,
  [379] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(122), 1,
      sym_variable,
    STATE(37), 1,
      aux_sym_function_repeat1,
    STATE(38), 1,
      sym_comment,
  [392] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(124), 1,
      sym_variable,
    STATE(38), 1,
      aux_sym_function_repeat1,
    STATE(39), 1,
      sym_comment,
  [405] = 4,
    ACTIONS(126), 1,
      anon_sym_PERCENT,
    ACTIONS(128), 1,
      aux_sym_comment_token1,
    STATE(34), 1,
      aux_sym_comment_repeat1,
    STATE(40), 1,
      sym_comment,
  [418] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(130), 1,
      sym_variable,
    STATE(37), 1,
      aux_sym_function_repeat1,
    STATE(41), 1,
      sym_comment,
  [431] = 3,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(132), 1,
      sym_variable,
    STATE(42), 1,
      sym_comment,
  [441] = 3,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(134), 1,
      anon_sym_RBRACK,
    STATE(43), 1,
      sym_comment,
  [451] = 3,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(136), 1,
      ts_builtin_sym_end,
    STATE(44), 1,
      sym_comment,
  [461] = 3,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(138), 1,
      sym_directive,
    STATE(45), 1,
      sym_comment,
  [471] = 3,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(140), 1,
      anon_sym_RBRACK,
    STATE(46), 1,
      sym_comment,
  [481] = 3,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(142), 1,
      sym_directive,
    STATE(47), 1,
      sym_comment,
  [491] = 1,
    ACTIONS(144), 1,
      ts_builtin_sym_end,
  [495] = 1,
    ACTIONS(146), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(16)] = 0,
  [SMALL_STATE(17)] = 20,
  [SMALL_STATE(18)] = 40,
  [SMALL_STATE(19)] = 60,
  [SMALL_STATE(20)] = 80,
  [SMALL_STATE(21)] = 100,
  [SMALL_STATE(22)] = 120,
  [SMALL_STATE(23)] = 140,
  [SMALL_STATE(24)] = 159,
  [SMALL_STATE(25)] = 178,
  [SMALL_STATE(26)] = 197,
  [SMALL_STATE(27)] = 216,
  [SMALL_STATE(28)] = 235,
  [SMALL_STATE(29)] = 254,
  [SMALL_STATE(30)] = 270,
  [SMALL_STATE(31)] = 286,
  [SMALL_STATE(32)] = 302,
  [SMALL_STATE(33)] = 318,
  [SMALL_STATE(34)] = 331,
  [SMALL_STATE(35)] = 342,
  [SMALL_STATE(36)] = 355,
  [SMALL_STATE(37)] = 368,
  [SMALL_STATE(38)] = 379,
  [SMALL_STATE(39)] = 392,
  [SMALL_STATE(40)] = 405,
  [SMALL_STATE(41)] = 418,
  [SMALL_STATE(42)] = 431,
  [SMALL_STATE(43)] = 441,
  [SMALL_STATE(44)] = 451,
  [SMALL_STATE(45)] = 461,
  [SMALL_STATE(46)] = 471,
  [SMALL_STATE(47)] = 481,
  [SMALL_STATE(48)] = 491,
  [SMALL_STATE(49)] = 495,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_application_repeat1, 2, 0, 8), SHIFT_REPEAT(33),
  [20] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_application_repeat1, 2, 0, 8), SHIFT_REPEAT(10),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_application_repeat1, 2, 0, 8), SHIFT_REPEAT(15),
  [26] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_application_repeat1, 2, 0, 8),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_application_repeat1, 2, 0, 8), SHIFT_REPEAT(45),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_application_repeat1, 2, 0, 8), SHIFT_REPEAT(19),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [38] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_application_repeat1, 1, 0, 3),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_application_repeat1, 1, 0, 3),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 4, 0, 5),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 4, 0, 5),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_application_repeat1, 2, 0, 6),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_application_repeat1, 2, 0, 6),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dire_loop, 3, 0, 4),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dire_loop, 3, 0, 4),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_application, 4, 0, 7),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_application, 4, 0, 7),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 5, 0, 9),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 5, 0, 9),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 1, 0, 1),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [119] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2, 0, 2), SHIFT_REPEAT(36),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [126] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2, 0, 1),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [136] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lprog(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "lprog",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
