/* Automatically @generated by tree-sitter v0.25.9 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 36
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 30
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 12
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACK = 1,
  anon_sym_RBRACK = 2,
  anon_sym_BSLASH = 3,
  anon_sym_COMMA = 4,
  anon_sym_DOT = 5,
  anon_sym_LPAREN = 6,
  anon_sym_RPAREN = 7,
  sym_comment = 8,
  sym_var_name = 9,
  sym_macro_name = 10,
  sym_string = 11,
  sym_expr_symbol = 12,
  sym_macro_symbol = 13,
  sym_source_file = 14,
  sym__element = 15,
  sym_global_macro = 16,
  sym_code_macro = 17,
  sym_include_statement = 18,
  sym__expression = 19,
  sym_expression = 20,
  sym_l_expression = 21,
  sym__l_expression = 22,
  sym_l_function = 23,
  sym_l_application = 24,
  sym_l_variable = 25,
  sym_l_macro = 26,
  aux_sym_source_file_repeat1 = 27,
  aux_sym_l_function_repeat1 = 28,
  aux_sym_l_application_repeat1 = 29,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_COMMA] = ",",
  [anon_sym_DOT] = ".",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_comment] = "comment",
  [sym_var_name] = "var_name",
  [sym_macro_name] = "macro_name",
  [sym_string] = "string",
  [sym_expr_symbol] = "expr_symbol",
  [sym_macro_symbol] = "macro_symbol",
  [sym_source_file] = "source_file",
  [sym__element] = "_element",
  [sym_global_macro] = "global_macro",
  [sym_code_macro] = "code_macro",
  [sym_include_statement] = "include_statement",
  [sym__expression] = "_expression",
  [sym_expression] = "expression",
  [sym_l_expression] = "l_expression",
  [sym__l_expression] = "_l_expression",
  [sym_l_function] = "l_function",
  [sym_l_application] = "l_application",
  [sym_l_variable] = "l_variable",
  [sym_l_macro] = "l_macro",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_l_function_repeat1] = "l_function_repeat1",
  [aux_sym_l_application_repeat1] = "l_application_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_comment] = sym_comment,
  [sym_var_name] = sym_var_name,
  [sym_macro_name] = sym_macro_name,
  [sym_string] = sym_string,
  [sym_expr_symbol] = sym_expr_symbol,
  [sym_macro_symbol] = sym_macro_symbol,
  [sym_source_file] = sym_source_file,
  [sym__element] = sym__element,
  [sym_global_macro] = sym_global_macro,
  [sym_code_macro] = sym_code_macro,
  [sym_include_statement] = sym_include_statement,
  [sym__expression] = sym__expression,
  [sym_expression] = sym_expression,
  [sym_l_expression] = sym_l_expression,
  [sym__l_expression] = sym__l_expression,
  [sym_l_function] = sym_l_function,
  [sym_l_application] = sym_l_application,
  [sym_l_variable] = sym_l_variable,
  [sym_l_macro] = sym_l_macro,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_l_function_repeat1] = aux_sym_l_function_repeat1,
  [aux_sym_l_application_repeat1] = aux_sym_l_application_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_var_name] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_name] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_expr_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__element] = {
    .visible = false,
    .named = true,
  },
  [sym_global_macro] = {
    .visible = true,
    .named = true,
  },
  [sym_code_macro] = {
    .visible = true,
    .named = true,
  },
  [sym_include_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_l_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__l_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_l_function] = {
    .visible = true,
    .named = true,
  },
  [sym_l_application] = {
    .visible = true,
    .named = true,
  },
  [sym_l_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_l_macro] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_l_function_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_l_application_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_arg = 1,
  field_body = 2,
  field_file_name = 3,
  field_function = 4,
  field_name = 5,
  field_symbol = 6,
  field_variable = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arg] = "arg",
  [field_body] = "body",
  [field_file_name] = "file_name",
  [field_function] = "function",
  [field_name] = "name",
  [field_symbol] = "symbol",
  [field_variable] = "variable",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 3},
  [6] = {.index = 9, .length = 2},
  [7] = {.index = 11, .length = 2},
  [8] = {.index = 13, .length = 1},
  [9] = {.index = 14, .length = 2},
  [10] = {.index = 16, .length = 2},
  [11] = {.index = 18, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_symbol, 0},
  [1] =
    {field_name, 0},
  [2] =
    {field_body, 1},
    {field_symbol, 0},
  [4] =
    {field_file_name, 1},
    {field_symbol, 0},
  [6] =
    {field_body, 2},
    {field_name, 1},
    {field_symbol, 0},
  [9] =
    {field_name, 1},
    {field_symbol, 0},
  [11] =
    {field_body, 3},
    {field_variable, 1},
  [13] =
    {field_arg, 1},
  [14] =
    {field_arg, 2, .inherited = true},
    {field_function, 1},
  [16] =
    {field_arg, 0, .inherited = true},
    {field_arg, 1, .inherited = true},
  [18] =
    {field_body, 4},
    {field_variable, 1},
    {field_variable, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '(') ADVANCE(18);
      if (lookahead == ')') ADVANCE(19);
      if (lookahead == ',') ADVANCE(16);
      if (lookahead == '.') ADVANCE(17);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '[') ADVANCE(13);
      if (lookahead == '\\') SKIP(10);
      if (lookahead == ']') ADVANCE(14);
      if (lookahead == '_') ADVANCE(24);
      if (lookahead == '%' ||
          lookahead == '*' ||
          lookahead == '@') ADVANCE(29);
      if (('#' <= lookahead && lookahead <= '&')) ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(26);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(4);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(4);
      if (lookahead == '\r') SKIP(1);
      END_STATE();
    case 3:
      if (lookahead == '\r') ADVANCE(23);
      if (lookahead == '\\') ADVANCE(21);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '\\') SKIP(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(26);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(27);
      if (('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(22);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '/') ADVANCE(20);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (eof) ADVANCE(12);
      if (lookahead == '\n') SKIP(0);
      END_STATE();
    case 10:
      if (eof) ADVANCE(12);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '\r') SKIP(9);
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '(', 18,
        '/', 6,
        '[', 13,
        '\\', 15,
        ']', 14,
        '_', 24,
        '%', 29,
        '*', 29,
        '@', 29,
        '#', 28,
        '$', 28,
        '&', 28,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(26);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\r') ADVANCE(23);
      if (lookahead == '\\') ADVANCE(21);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == '_') ADVANCE(24);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(26);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_var_name);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_macro_name);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_expr_symbol);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_macro_symbol);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 11},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 11},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 11},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 11},
  [9] = {.lex_state = 11},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 11},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_var_name] = ACTIONS(1),
    [sym_macro_name] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_expr_symbol] = ACTIONS(1),
    [sym_macro_symbol] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(34),
    [sym__element] = STATE(5),
    [sym_global_macro] = STATE(5),
    [sym_code_macro] = STATE(5),
    [sym_include_statement] = STATE(5),
    [sym_expression] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [sym_expr_symbol] = ACTIONS(7),
    [sym_macro_symbol] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym__expression] = STATE(18),
    [sym_expression] = STATE(18),
    [sym_l_expression] = STATE(18),
    [sym__l_expression] = STATE(20),
    [sym_l_function] = STATE(20),
    [sym_l_application] = STATE(20),
    [sym_l_variable] = STATE(20),
    [sym_l_macro] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(13),
    [anon_sym_BSLASH] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [sym_comment] = ACTIONS(19),
    [sym_var_name] = ACTIONS(21),
    [sym_macro_name] = ACTIONS(23),
    [sym_expr_symbol] = ACTIONS(25),
    [sym_macro_symbol] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      sym_expr_symbol,
    ACTIONS(32), 1,
      sym_macro_symbol,
    ACTIONS(27), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
    STATE(3), 6,
      sym__element,
      sym_global_macro,
      sym_code_macro,
      sym_include_statement,
      sym_expression,
      aux_sym_source_file_repeat1,
  [22] = 7,
    ACTIONS(15), 1,
      anon_sym_BSLASH,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(21), 1,
      sym_var_name,
    ACTIONS(23), 1,
      sym_macro_name,
    ACTIONS(35), 1,
      anon_sym_LBRACK,
    STATE(17), 5,
      sym__l_expression,
      sym_l_function,
      sym_l_application,
      sym_l_variable,
      sym_l_macro,
  [48] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_expr_symbol,
    ACTIONS(9), 1,
      sym_macro_symbol,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    STATE(3), 6,
      sym__element,
      sym_global_macro,
      sym_code_macro,
      sym_include_statement,
      sym_expression,
      aux_sym_source_file_repeat1,
  [69] = 6,
    ACTIONS(15), 1,
      anon_sym_BSLASH,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(21), 1,
      sym_var_name,
    ACTIONS(23), 1,
      sym_macro_name,
    STATE(29), 5,
      sym__l_expression,
      sym_l_function,
      sym_l_application,
      sym_l_variable,
      sym_l_macro,
  [92] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_expr_symbol,
    ACTIONS(9), 1,
      sym_macro_symbol,
    ACTIONS(39), 1,
      anon_sym_RBRACK,
    STATE(10), 6,
      sym__element,
      sym_global_macro,
      sym_code_macro,
      sym_include_statement,
      sym_expression,
      aux_sym_source_file_repeat1,
  [113] = 6,
    ACTIONS(15), 1,
      anon_sym_BSLASH,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(21), 1,
      sym_var_name,
    ACTIONS(23), 1,
      sym_macro_name,
    STATE(13), 5,
      sym__l_expression,
      sym_l_function,
      sym_l_application,
      sym_l_variable,
      sym_l_macro,
  [136] = 6,
    ACTIONS(15), 1,
      anon_sym_BSLASH,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(21), 1,
      sym_var_name,
    ACTIONS(23), 1,
      sym_macro_name,
    STATE(32), 5,
      sym__l_expression,
      sym_l_function,
      sym_l_application,
      sym_l_variable,
      sym_l_macro,
  [159] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_expr_symbol,
    ACTIONS(9), 1,
      sym_macro_symbol,
    ACTIONS(41), 1,
      anon_sym_RBRACK,
    STATE(3), 6,
      sym__element,
      sym_global_macro,
      sym_code_macro,
      sym_include_statement,
      sym_expression,
      aux_sym_source_file_repeat1,
  [180] = 6,
    ACTIONS(15), 1,
      anon_sym_BSLASH,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(21), 1,
      sym_var_name,
    ACTIONS(23), 1,
      sym_macro_name,
    STATE(16), 5,
      sym__l_expression,
      sym_l_function,
      sym_l_application,
      sym_l_variable,
      sym_l_macro,
  [203] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 7,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_RPAREN,
      sym_expr_symbol,
      sym_macro_symbol,
  [216] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 6,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_expr_symbol,
      sym_macro_symbol,
  [228] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 6,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_expr_symbol,
      sym_macro_symbol,
  [240] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 6,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_expr_symbol,
      sym_macro_symbol,
  [252] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 6,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_expr_symbol,
      sym_macro_symbol,
  [264] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      sym_expr_symbol,
      sym_macro_symbol,
  [274] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      sym_expr_symbol,
      sym_macro_symbol,
  [284] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      sym_expr_symbol,
      sym_macro_symbol,
  [294] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      sym_expr_symbol,
      sym_macro_symbol,
  [304] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      sym_expr_symbol,
      sym_macro_symbol,
  [314] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      sym_expr_symbol,
      sym_macro_symbol,
  [324] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      sym_var_name,
    STATE(24), 1,
      aux_sym_l_function_repeat1,
    STATE(28), 1,
      sym_l_variable,
  [337] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      sym_var_name,
    STATE(24), 1,
      aux_sym_l_function_repeat1,
    STATE(35), 1,
      sym_l_variable,
  [350] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      sym_var_name,
    STATE(23), 1,
      aux_sym_l_function_repeat1,
    STATE(31), 1,
      sym_l_variable,
  [363] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_COMMA,
    ACTIONS(72), 1,
      anon_sym_RPAREN,
    STATE(27), 1,
      aux_sym_l_application_repeat1,
  [376] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      anon_sym_COMMA,
    ACTIONS(77), 1,
      anon_sym_RPAREN,
    STATE(27), 1,
      aux_sym_l_application_repeat1,
  [389] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_COMMA,
    ACTIONS(81), 1,
      anon_sym_DOT,
  [399] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_COMMA,
    STATE(26), 1,
      aux_sym_l_application_repeat1,
  [409] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      sym_macro_name,
    ACTIONS(85), 1,
      sym_string,
  [419] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_COMMA,
    ACTIONS(87), 1,
      anon_sym_DOT,
  [429] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [437] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      sym_var_name,
  [444] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      ts_builtin_sym_end,
  [451] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_COMMA,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 22,
  [SMALL_STATE(5)] = 48,
  [SMALL_STATE(6)] = 69,
  [SMALL_STATE(7)] = 92,
  [SMALL_STATE(8)] = 113,
  [SMALL_STATE(9)] = 136,
  [SMALL_STATE(10)] = 159,
  [SMALL_STATE(11)] = 180,
  [SMALL_STATE(12)] = 203,
  [SMALL_STATE(13)] = 216,
  [SMALL_STATE(14)] = 228,
  [SMALL_STATE(15)] = 240,
  [SMALL_STATE(16)] = 252,
  [SMALL_STATE(17)] = 264,
  [SMALL_STATE(18)] = 274,
  [SMALL_STATE(19)] = 284,
  [SMALL_STATE(20)] = 294,
  [SMALL_STATE(21)] = 304,
  [SMALL_STATE(22)] = 314,
  [SMALL_STATE(23)] = 324,
  [SMALL_STATE(24)] = 337,
  [SMALL_STATE(25)] = 350,
  [SMALL_STATE(26)] = 363,
  [SMALL_STATE(27)] = 376,
  [SMALL_STATE(28)] = 389,
  [SMALL_STATE(29)] = 399,
  [SMALL_STATE(30)] = 409,
  [SMALL_STATE(31)] = 419,
  [SMALL_STATE(32)] = 429,
  [SMALL_STATE(33)] = 437,
  [SMALL_STATE(34)] = 444,
  [SMALL_STATE(35)] = 451,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 1),
  [13] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 1),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_l_variable, 1, 0, 2),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_l_function, 4, 0, 7),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_l_macro, 1, 0, 2),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_l_application, 4, 0, 9),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_l_function, 5, 0, 11),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_macro, 3, 0, 5),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 2, 0, 3),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global_macro, 4, 0, 6),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_l_expression, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_statement, 2, 0, 4),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global_macro, 5, 0, 6),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_l_function_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_l_application_repeat1, 2, 0, 10), SHIFT_REPEAT(9),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_l_application_repeat1, 2, 0, 10),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_l_application_repeat1, 2, 0, 8),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_l_function_repeat1, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lprog(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "lprog",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
