/* Automatically @generated by tree-sitter v0.25.9 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 43
#define LARGE_STATE_COUNT 11
#define SYMBOL_COUNT 21
#define ALIAS_COUNT 0
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 8
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_BSLASH = 1,
  anon_sym_COMMA = 2,
  anon_sym_DOT = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_PERCENT = 6,
  aux_sym_comment_token1 = 7,
  sym_variable = 8,
  sym_macro = 9,
  sym_string = 10,
  sym_directive = 11,
  sym_source_file = 12,
  sym__expression = 13,
  sym_function = 14,
  sym_application = 15,
  sym_comment = 16,
  aux_sym_source_file_repeat1 = 17,
  aux_sym_function_repeat1 = 18,
  aux_sym_application_repeat1 = 19,
  aux_sym_comment_repeat1 = 20,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_COMMA] = ",",
  [anon_sym_DOT] = ".",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_PERCENT] = "%",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_variable] = "variable",
  [sym_macro] = "macro",
  [sym_string] = "string",
  [sym_directive] = "directive",
  [sym_source_file] = "source_file",
  [sym__expression] = "_expression",
  [sym_function] = "function",
  [sym_application] = "application",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_function_repeat1] = "function_repeat1",
  [aux_sym_application_repeat1] = "application_repeat1",
  [aux_sym_comment_repeat1] = "comment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_variable] = sym_variable,
  [sym_macro] = sym_macro,
  [sym_string] = sym_string,
  [sym_directive] = sym_directive,
  [sym_source_file] = sym_source_file,
  [sym__expression] = sym__expression,
  [sym_function] = sym_function,
  [sym_application] = sym_application,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_function_repeat1] = aux_sym_function_repeat1,
  [aux_sym_application_repeat1] = aux_sym_application_repeat1,
  [aux_sym_comment_repeat1] = aux_sym_comment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_macro] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_application] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_application_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_arg = 1,
  field_body = 2,
  field_function = 3,
  field_variable = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arg] = "arg",
  [field_body] = "body",
  [field_function] = "function",
  [field_variable] = "variable",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 1},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 2},
  [7] = {.index = 10, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_variable, 0},
  [1] =
    {field_variable, 0, .inherited = true},
    {field_variable, 1, .inherited = true},
  [3] =
    {field_body, 3},
    {field_variable, 1},
  [5] =
    {field_arg, 1},
  [6] =
    {field_arg, 2, .inherited = true},
    {field_function, 1},
  [8] =
    {field_arg, 0, .inherited = true},
    {field_arg, 1, .inherited = true},
  [10] =
    {field_body, 4},
    {field_variable, 1, .inherited = true},
    {field_variable, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 4,
  [9] = 7,
  [10] = 5,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 16,
  [19] = 14,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 12,
  [28] = 13,
  [29] = 15,
  [30] = 30,
  [31] = 31,
  [32] = 21,
  [33] = 22,
  [34] = 34,
  [35] = 25,
  [36] = 26,
  [37] = 31,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '%') ADVANCE(15);
      if (lookahead == '(') ADVANCE(13);
      if (lookahead == ')') ADVANCE(14);
      if (lookahead == ',') ADVANCE(11);
      if (lookahead == '.') ADVANCE(12);
      if (lookahead == '\\') SKIP(7);
      if (lookahead == '_') ADVANCE(18);
      if (('#' <= lookahead && lookahead <= '&') ||
          lookahead == '*' ||
          lookahead == '@') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(20);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(4);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(4);
      if (lookahead == '\r') SKIP(1);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(21);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '%') ADVANCE(15);
      if (lookahead == '\\') SKIP(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 5:
      if (lookahead == '%') ADVANCE(15);
      if (lookahead == '\\') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 6:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') SKIP(0);
      END_STATE();
    case 7:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '\r') SKIP(6);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '"', 3,
        '%', 15,
        '(', 13,
        '\\', 10,
        '_', 18,
        '#', 22,
        '$', 22,
        '&', 22,
        '*', 22,
        '@', 22,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(20);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\\') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '%') ADVANCE(16);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '_') ADVANCE(18);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(20);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_macro);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_directive);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 8},
  [2] = {.lex_state = 8},
  [3] = {.lex_state = 8},
  [4] = {.lex_state = 8},
  [5] = {.lex_state = 8},
  [6] = {.lex_state = 8},
  [7] = {.lex_state = 8},
  [8] = {.lex_state = 8},
  [9] = {.lex_state = 8},
  [10] = {.lex_state = 8},
  [11] = {.lex_state = 8},
  [12] = {.lex_state = 8},
  [13] = {.lex_state = 8},
  [14] = {.lex_state = 8},
  [15] = {.lex_state = 8},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 4},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 5},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 5},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 5},
  [35] = {.lex_state = 4},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 4},
  [41] = {(TSStateId)(-1),},
  [42] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(3),
    [sym_variable] = ACTIONS(1),
    [sym_macro] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_directive] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(39),
    [sym__expression] = STATE(11),
    [sym_function] = STATE(12),
    [sym_application] = STATE(12),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_BSLASH] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_PERCENT] = ACTIONS(11),
    [sym_variable] = ACTIONS(13),
    [sym_macro] = ACTIONS(13),
    [sym_string] = ACTIONS(13),
    [sym_directive] = ACTIONS(13),
  },
  [STATE(2)] = {
    [sym__expression] = STATE(11),
    [sym_function] = STATE(12),
    [sym_application] = STATE(12),
    [sym_comment] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_BSLASH] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_PERCENT] = ACTIONS(11),
    [sym_variable] = ACTIONS(13),
    [sym_macro] = ACTIONS(13),
    [sym_string] = ACTIONS(13),
    [sym_directive] = ACTIONS(13),
  },
  [STATE(3)] = {
    [sym__expression] = STATE(11),
    [sym_function] = STATE(12),
    [sym_application] = STATE(12),
    [sym_comment] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(17),
    [anon_sym_BSLASH] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(22),
    [anon_sym_PERCENT] = ACTIONS(11),
    [sym_variable] = ACTIONS(25),
    [sym_macro] = ACTIONS(25),
    [sym_string] = ACTIONS(25),
    [sym_directive] = ACTIONS(25),
  },
  [STATE(4)] = {
    [sym__expression] = STATE(15),
    [sym_function] = STATE(12),
    [sym_application] = STATE(12),
    [sym_comment] = STATE(4),
    [anon_sym_BSLASH] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_PERCENT] = ACTIONS(11),
    [sym_variable] = ACTIONS(13),
    [sym_macro] = ACTIONS(13),
    [sym_string] = ACTIONS(13),
    [sym_directive] = ACTIONS(13),
  },
  [STATE(5)] = {
    [sym__expression] = STATE(26),
    [sym_function] = STATE(27),
    [sym_application] = STATE(27),
    [sym_comment] = STATE(5),
    [anon_sym_BSLASH] = ACTIONS(28),
    [anon_sym_LPAREN] = ACTIONS(30),
    [anon_sym_PERCENT] = ACTIONS(11),
    [sym_variable] = ACTIONS(32),
    [sym_macro] = ACTIONS(32),
    [sym_string] = ACTIONS(32),
    [sym_directive] = ACTIONS(32),
  },
  [STATE(6)] = {
    [sym__expression] = STATE(24),
    [sym_function] = STATE(27),
    [sym_application] = STATE(27),
    [sym_comment] = STATE(6),
    [anon_sym_BSLASH] = ACTIONS(28),
    [anon_sym_LPAREN] = ACTIONS(30),
    [anon_sym_PERCENT] = ACTIONS(11),
    [sym_variable] = ACTIONS(32),
    [sym_macro] = ACTIONS(32),
    [sym_string] = ACTIONS(32),
    [sym_directive] = ACTIONS(32),
  },
  [STATE(7)] = {
    [sym__expression] = STATE(14),
    [sym_function] = STATE(12),
    [sym_application] = STATE(12),
    [sym_comment] = STATE(7),
    [anon_sym_BSLASH] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_PERCENT] = ACTIONS(11),
    [sym_variable] = ACTIONS(13),
    [sym_macro] = ACTIONS(13),
    [sym_string] = ACTIONS(13),
    [sym_directive] = ACTIONS(13),
  },
  [STATE(8)] = {
    [sym__expression] = STATE(29),
    [sym_function] = STATE(27),
    [sym_application] = STATE(27),
    [sym_comment] = STATE(8),
    [anon_sym_BSLASH] = ACTIONS(28),
    [anon_sym_LPAREN] = ACTIONS(30),
    [anon_sym_PERCENT] = ACTIONS(11),
    [sym_variable] = ACTIONS(32),
    [sym_macro] = ACTIONS(32),
    [sym_string] = ACTIONS(32),
    [sym_directive] = ACTIONS(32),
  },
  [STATE(9)] = {
    [sym__expression] = STATE(19),
    [sym_function] = STATE(27),
    [sym_application] = STATE(27),
    [sym_comment] = STATE(9),
    [anon_sym_BSLASH] = ACTIONS(28),
    [anon_sym_LPAREN] = ACTIONS(30),
    [anon_sym_PERCENT] = ACTIONS(11),
    [sym_variable] = ACTIONS(32),
    [sym_macro] = ACTIONS(32),
    [sym_string] = ACTIONS(32),
    [sym_directive] = ACTIONS(32),
  },
  [STATE(10)] = {
    [sym__expression] = STATE(36),
    [sym_function] = STATE(27),
    [sym_application] = STATE(27),
    [sym_comment] = STATE(10),
    [anon_sym_BSLASH] = ACTIONS(28),
    [anon_sym_LPAREN] = ACTIONS(30),
    [anon_sym_PERCENT] = ACTIONS(11),
    [sym_variable] = ACTIONS(32),
    [sym_macro] = ACTIONS(32),
    [sym_string] = ACTIONS(32),
    [sym_directive] = ACTIONS(32),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(11), 1,
      anon_sym_PERCENT,
    STATE(11), 1,
      sym_comment,
    ACTIONS(34), 2,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
    ACTIONS(36), 5,
      anon_sym_LPAREN,
      sym_variable,
      sym_macro,
      sym_string,
      sym_directive,
  [18] = 4,
    ACTIONS(11), 1,
      anon_sym_PERCENT,
    STATE(12), 1,
      sym_comment,
    ACTIONS(38), 2,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
    ACTIONS(40), 5,
      anon_sym_LPAREN,
      sym_variable,
      sym_macro,
      sym_string,
      sym_directive,
  [36] = 4,
    ACTIONS(11), 1,
      anon_sym_PERCENT,
    STATE(13), 1,
      sym_comment,
    ACTIONS(42), 2,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
    ACTIONS(44), 5,
      anon_sym_LPAREN,
      sym_variable,
      sym_macro,
      sym_string,
      sym_directive,
  [54] = 4,
    ACTIONS(11), 1,
      anon_sym_PERCENT,
    STATE(14), 1,
      sym_comment,
    ACTIONS(46), 2,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
    ACTIONS(48), 5,
      anon_sym_LPAREN,
      sym_variable,
      sym_macro,
      sym_string,
      sym_directive,
  [72] = 4,
    ACTIONS(11), 1,
      anon_sym_PERCENT,
    STATE(15), 1,
      sym_comment,
    ACTIONS(50), 2,
      ts_builtin_sym_end,
      anon_sym_BSLASH,
    ACTIONS(52), 5,
      anon_sym_LPAREN,
      sym_variable,
      sym_macro,
      sym_string,
      sym_directive,
  [90] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(54), 1,
      anon_sym_COMMA,
    ACTIONS(56), 1,
      anon_sym_RPAREN,
    STATE(16), 1,
      sym_comment,
    STATE(17), 1,
      aux_sym_application_repeat1,
  [106] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(58), 1,
      anon_sym_COMMA,
    ACTIONS(61), 1,
      anon_sym_RPAREN,
    STATE(17), 2,
      sym_comment,
      aux_sym_application_repeat1,
  [120] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(54), 1,
      anon_sym_COMMA,
    ACTIONS(63), 1,
      anon_sym_RPAREN,
    STATE(17), 1,
      aux_sym_application_repeat1,
    STATE(18), 1,
      sym_comment,
  [136] = 3,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    STATE(19), 1,
      sym_comment,
    ACTIONS(46), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [147] = 3,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(65), 1,
      sym_variable,
    STATE(20), 2,
      sym_comment,
      aux_sym_function_repeat1,
  [158] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(68), 1,
      sym_variable,
    STATE(21), 1,
      sym_comment,
    STATE(25), 1,
      aux_sym_function_repeat1,
  [171] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(70), 1,
      anon_sym_COMMA,
    ACTIONS(72), 1,
      anon_sym_DOT,
    STATE(22), 1,
      sym_comment,
  [184] = 4,
    ACTIONS(74), 1,
      anon_sym_PERCENT,
    ACTIONS(76), 1,
      aux_sym_comment_token1,
    STATE(23), 1,
      sym_comment,
    STATE(30), 1,
      aux_sym_comment_repeat1,
  [197] = 3,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    STATE(24), 1,
      sym_comment,
    ACTIONS(78), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [208] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(80), 1,
      sym_variable,
    STATE(20), 1,
      aux_sym_function_repeat1,
    STATE(25), 1,
      sym_comment,
  [221] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(54), 1,
      anon_sym_COMMA,
    STATE(16), 1,
      aux_sym_application_repeat1,
    STATE(26), 1,
      sym_comment,
  [234] = 3,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    STATE(27), 1,
      sym_comment,
    ACTIONS(38), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [245] = 3,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    STATE(28), 1,
      sym_comment,
    ACTIONS(42), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [256] = 3,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    STATE(29), 1,
      sym_comment,
    ACTIONS(50), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [267] = 3,
    ACTIONS(82), 1,
      anon_sym_PERCENT,
    ACTIONS(84), 1,
      aux_sym_comment_token1,
    STATE(30), 2,
      sym_comment,
      aux_sym_comment_repeat1,
  [278] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(70), 1,
      anon_sym_COMMA,
    ACTIONS(87), 1,
      anon_sym_DOT,
    STATE(31), 1,
      sym_comment,
  [291] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(89), 1,
      sym_variable,
    STATE(32), 1,
      sym_comment,
    STATE(35), 1,
      aux_sym_function_repeat1,
  [304] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(70), 1,
      anon_sym_COMMA,
    ACTIONS(91), 1,
      anon_sym_DOT,
    STATE(33), 1,
      sym_comment,
  [317] = 4,
    ACTIONS(93), 1,
      anon_sym_PERCENT,
    ACTIONS(95), 1,
      aux_sym_comment_token1,
    STATE(23), 1,
      aux_sym_comment_repeat1,
    STATE(34), 1,
      sym_comment,
  [330] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(97), 1,
      sym_variable,
    STATE(20), 1,
      aux_sym_function_repeat1,
    STATE(35), 1,
      sym_comment,
  [343] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(54), 1,
      anon_sym_COMMA,
    STATE(18), 1,
      aux_sym_application_repeat1,
    STATE(36), 1,
      sym_comment,
  [356] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(70), 1,
      anon_sym_COMMA,
    ACTIONS(99), 1,
      anon_sym_DOT,
    STATE(37), 1,
      sym_comment,
  [369] = 3,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(70), 1,
      anon_sym_COMMA,
    STATE(38), 1,
      sym_comment,
  [379] = 3,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(101), 1,
      ts_builtin_sym_end,
    STATE(39), 1,
      sym_comment,
  [389] = 3,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(103), 1,
      sym_variable,
    STATE(40), 1,
      sym_comment,
  [399] = 1,
    ACTIONS(105), 1,
      ts_builtin_sym_end,
  [403] = 1,
    ACTIONS(107), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(11)] = 0,
  [SMALL_STATE(12)] = 18,
  [SMALL_STATE(13)] = 36,
  [SMALL_STATE(14)] = 54,
  [SMALL_STATE(15)] = 72,
  [SMALL_STATE(16)] = 90,
  [SMALL_STATE(17)] = 106,
  [SMALL_STATE(18)] = 120,
  [SMALL_STATE(19)] = 136,
  [SMALL_STATE(20)] = 147,
  [SMALL_STATE(21)] = 158,
  [SMALL_STATE(22)] = 171,
  [SMALL_STATE(23)] = 184,
  [SMALL_STATE(24)] = 197,
  [SMALL_STATE(25)] = 208,
  [SMALL_STATE(26)] = 221,
  [SMALL_STATE(27)] = 234,
  [SMALL_STATE(28)] = 245,
  [SMALL_STATE(29)] = 256,
  [SMALL_STATE(30)] = 267,
  [SMALL_STATE(31)] = 278,
  [SMALL_STATE(32)] = 291,
  [SMALL_STATE(33)] = 304,
  [SMALL_STATE(34)] = 317,
  [SMALL_STATE(35)] = 330,
  [SMALL_STATE(36)] = 343,
  [SMALL_STATE(37)] = 356,
  [SMALL_STATE(38)] = 369,
  [SMALL_STATE(39)] = 379,
  [SMALL_STATE(40)] = 389,
  [SMALL_STATE(41)] = 399,
  [SMALL_STATE(42)] = 403,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [30] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [32] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_application, 4, 0, 5),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_application, 4, 0, 5),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 5, 0, 7),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 5, 0, 7),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 4, 0, 3),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 4, 0, 3),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_application_repeat1, 2, 0, 6), SHIFT_REPEAT(6),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_application_repeat1, 2, 0, 6),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2, 0, 2), SHIFT_REPEAT(38),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_application_repeat1, 2, 0, 4),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [101] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2, 0, 1),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lprog(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "lprog",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
